buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://s3-eu-west-1.amazonaws.com/beekeeper-marketplace-sdk/maven2/release/' }
        maven {
            url 'https://nexus.internal.beekeeper.io/repository/beekeeper-maven-central/'
            credentials {
                username = System.getenv('NEXUS_USERNAME') ?: (project.hasProperty('NEXUS_USERNAME') ? project.property('NEXUS_USERNAME') : "")
                password = System.getenv('NEXUS_PASSWORD') ?: (project.hasProperty('NEXUS_PASSWORD') ? project.property('NEXUS_PASSWORD') : "")
            }
        }
    }
    dependencies {
        classpath "io.beekeeper:connector-plugin:${sdkVersion}"
        classpath "io.beekeeper:connector-default-mapping-plugin:${sdkVersion}"
    }
}

plugins {
    id 'io.franzbecker.gradle-lombok' version '5.0.0'
    id 'io.beekeeper.gradle.plugin' version '0.9.24'
}

ext {
    nexusUsername = System.getenv('NEXUS_USERNAME') ?: (project.hasProperty('NEXUS_USERNAME') ? project.property('NEXUS_USERNAME') : "")
    nexusPassword = System.getenv('NEXUS_PASSWORD') ?: (project.hasProperty('NEXUS_PASSWORD') ? project.property('NEXUS_PASSWORD') : "")
}

subprojects {
    group 'io.beekeeper'
    version '0.0.1'

    apply plugin: 'io.franzbecker.gradle-lombok'

    lombok {
        version = '1.18.30'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://clojars.org/repo" }
        maven { url 'https://s3-eu-west-1.amazonaws.com/beekeeper-marketplace-sdk/maven2/release/' }
        maven {
            url 'https://nexus.internal.beekeeper.io/repository/beekeeper-maven-central/'
            credentials {
                username = rootProject.ext.nexusUsername
                password = rootProject.ext.nexusPassword
            }
        }
    }

    dependencyCheck {
        analyzers {
            retirejs {
                enabled = false
            }
        }
    }
}
