version: '2.2'

services:
  marketplace-connector-usersync-sample:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXUS_USERNAME
        - NEXUS_PASSWORD
    env_file:
      - dev.stack.static.env
      - dev.stack.local.env

networks:
  default:
    external:
      name: beekeeperstack_default
